"""Protected persistent adapter for the existing TenantSecretReferences boundary.

No service/registry/ordinary DB schema. One private encrypted record per tenant
and environment; key is independently installed, never generated by this code.
Native key/file protection is Linux-only; offline tests inject synthetic codecs.
"""
from contextlib import contextmanager
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import threading
import uuid
from datetime import datetime, timezone

from app.tenant_secret_reference import SecretReferenceError, validate_reference

PROVIDER = 'wechat'
NAME = 'wechat-account'


def blocked(code='WECHAT_SECRET_BACKEND_BLOCKED'):
    return SecretReferenceError(code)


class ProtectedTenantSecretBackend:
    def __init__(self, root, environment, key_file, *, codec_loader=None):
        from app.tenant_secret_reference import ENVIRONMENTS
        if environment not in ENVIRONMENTS: raise blocked()
        self.root, self.environment = Path(root).absolute(), environment
        self.key_file = Path(key_file).absolute() if key_file else None
        self._codec_loader = codec_loader or self._native_codec
        self._thread_lock = threading.RLock()

    def _native_codec(self):
        try:
            from cryptography.fernet import Fernet
            if os.name != 'posix' or not self.key_file: raise ValueError()
            source = Path(__file__).resolve().parents[2]
            resolved = self.key_file.resolve(strict=True)
            if (resolved.is_relative_to(self.root.resolve()) or resolved.is_relative_to(source)
                    or any(path.is_symlink() for path in (self.key_file, *self.key_file.parents))):
                raise ValueError()
            for ancestor in self.key_file.parents:
                info = ancestor.stat()
                if info.st_uid not in (0, os.getuid()) or stat.S_IMODE(info.st_mode) & 0o022: raise ValueError()
            info = self.key_file.stat()
            parent = self.key_file.parent.stat()
            if (not stat.S_ISREG(info.st_mode) or stat.S_IMODE(info.st_mode) != 0o600
                    or info.st_uid not in (0, os.getuid()) or parent.st_uid not in (0, os.getuid())
                    or stat.S_IMODE(parent.st_mode) & 0o077): raise ValueError()
            fd = os.open(self.key_file, os.O_RDONLY | os.O_NOFOLLOW)
            with os.fdopen(fd, 'rb') as stream:
                current = os.fstat(stream.fileno())
                if (current.st_dev,current.st_ino) != (info.st_dev,info.st_ino): raise ValueError()
                raw = stream.read(256)
            return Fernet(raw.strip())
        except Exception: raise blocked() from None

    def _scope(self, tenant):
        if not isinstance(tenant, str) or not 0 < len(tenant) <= 128: raise blocked()
        return dict(tenant_id=tenant, environment=self.environment, provider=PROVIDER, name=NAME)

    @contextmanager
    def _locked(self, tenant):
        self._scope(tenant)
        try:
            codec = self._codec_loader()  # No directory or ciphertext writes without a key.
            if any(path.is_symlink() for path in (self.root, *self.root.parents)): raise ValueError()
            if os.name == 'posix':
                for ancestor in self.root.parents:
                    if ancestor.exists():
                        info = ancestor.stat()
                        if info.st_uid not in (0, os.getuid()) or stat.S_IMODE(info.st_mode) & 0o022:
                            # Synthetic test fixtures intentionally live under /tmp.
                            if self._codec_loader == self._native_codec: raise ValueError()
            self.root.mkdir(mode=0o700, parents=True, exist_ok=True)
            if os.name == 'posix':
                info = self.root.stat()
                if info.st_uid not in (0, os.getuid()) or stat.S_IMODE(info.st_mode) & 0o077: raise ValueError()
                if self._codec_loader == self._native_codec:
                    # parents=True uses the process umask for newly created
                    # ancestors, so recheck them before any encrypted write.
                    for ancestor in self.root.parents:
                        info = ancestor.stat()
                        if info.st_uid not in (0,os.getuid()) or stat.S_IMODE(info.st_mode) & 0o022: raise ValueError()
            name = hashlib.sha256(tenant.encode()).hexdigest()
            with self._thread_lock:
                fd = os.open(self.root / (name + '.lock'), os.O_CREAT | os.O_RDWR | getattr(os, 'O_NOFOLLOW', 0), 0o600)
                with os.fdopen(fd, 'a+b') as lock:
                    if os.name == 'posix':
                        import fcntl
                        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
                    else:  # Only synthetic-key offline Windows fixtures use this branch.
                        import msvcrt
                        lock.seek(0); lock.write(b'0'); lock.flush(); lock.seek(0)
                        msvcrt.locking(lock.fileno(), msvcrt.LK_LOCK, 1)
                    try: yield self.root / (name + '.fernet'), codec
                    finally:
                        if os.name == 'posix': fcntl.flock(lock.fileno(), fcntl.LOCK_UN)
                        else:
                            lock.seek(0); msvcrt.locking(lock.fileno(), msvcrt.LK_UNLCK, 1)
        except SecretReferenceError: raise
        except Exception: raise blocked() from None

    def _read(self, path, codec, tenant):
        if path.is_symlink(): raise blocked()
        if not path.exists(): return None
        if path.stat().st_size > 32768: raise blocked()
        if os.name == 'posix' and (stat.S_IMODE(path.stat().st_mode) != 0o600
                or path.stat().st_uid not in (0,os.getuid())): raise blocked()
        value = json.loads(codec.decrypt(path.read_bytes()))
        if (not {'scope','version','state','app_id','verification_status','secret'} <= set(value)
                or set(value)-{'scope','version','state','app_id','verification_status','secret','verified_at','verification_error_code'}
                or value['scope'] != self._scope(tenant) or type(value['version']) is not int
                or value['version'] < 1 or value['state'] not in ('active','revoked')
                or value['verification_status'] not in ('unverified','connected','failed','revoked')): raise blocked()
        return value

    def _write(self, path, codec, value):
        raw = codec.encrypt(json.dumps(value, separators=(',', ':'), allow_nan=False).encode())
        temp = path.with_name(path.name + '.' + uuid.uuid4().hex + '.tmp')
        fd = os.open(temp, os.O_CREAT | os.O_EXCL | os.O_WRONLY | getattr(os, 'O_NOFOLLOW', 0), 0o600)
        with os.fdopen(fd, 'wb') as stream:
            stream.write(raw); stream.flush(); os.fsync(stream.fileno())
        os.replace(temp, path)
        if os.name == 'posix':
            fd = os.open(self.root, os.O_RDONLY | os.O_DIRECTORY)
            try: os.fsync(fd)
            finally: os.close(fd)

    def _reference(self, record):
        return dict(record['scope'], version=record['version'])

    def save(self, tenant, app_id, secret, *, expected=None):
        """PROVISION or ROTATE; empty secret retains existing value, never reconnects."""
        try:
            if not isinstance(app_id,str) or not re.fullmatch(r'wx[a-zA-Z0-9]{16}',app_id):
                raise blocked('WECHAT_SECRET_INPUT_INVALID')
            if secret is not None and (not isinstance(secret, str) or not 8 <= len(secret) <= 512): raise blocked('WECHAT_SECRET_INPUT_INVALID')
            with self._locked(tenant) as (path, codec):
                old = self._read(path, codec, tenant)
                if expected is not None:
                    validate_reference(expected, tenant, environment=self.environment)
                    if not old or expected != self._reference(old): raise blocked('WECHAT_SECRET_VERSION_CONFLICT')
                if secret is None:
                    if not old or old['state'] != 'active': raise blocked('WECHAT_CREDENTIAL_REFERENCE_UNAVAILABLE')
                    if old['app_id'] == app_id: return self._reference(old)
                    secret = old['secret']
                value = dict(scope=self._scope(tenant), version=(old['version'] if old else 0)+1,
                    state='active', app_id=app_id, verification_status='unverified', secret=secret)
                self._write(path, codec, value)
                return self._reference(value)
        except SecretReferenceError: raise
        except Exception: raise blocked() from None

    def rotate(self, tenant, reference, app_id, secret):
        return self.save(tenant, app_id, secret, expected=reference)

    def revoke(self, tenant):
        with self._locked(tenant) as (path, codec):
            old = self._read(path, codec, tenant)
            if old is None: return
            value = dict(old, version=old['version']+1, state='revoked', secret=None, verification_status='revoked')
            self._write(path, codec, value)

    def _current(self, tenant, reference, app_id, *, connected=False):
        validate_reference(reference, tenant, environment=self.environment)
        if reference['provider'] != PROVIDER: raise blocked('WECHAT_CREDENTIAL_REFERENCE_UNAVAILABLE')
        with self._locked(tenant) as (path, codec):
            value = self._read(path, codec, tenant)
            if (not value or value['state'] != 'active' or reference != self._reference(value)
                    or value['app_id'] != app_id or not isinstance(value['secret'], str)):
                raise blocked('WECHAT_CREDENTIAL_REFERENCE_UNAVAILABLE')
            if connected and value['verification_status'] != 'connected': raise blocked('WECHAT_ACCOUNT_NOT_CONNECTED')
            return value

    def resolve(self, tenant, reference, app_id, *, connected=False):
        # No process cache. Each call reads current authenticated version/state.
        return self._current(tenant, reference, app_id, connected=connected)['secret']

    def status(self, tenant, reference, app_id):
        value = self._current(tenant, reference, app_id)
        return dict(configured=True, verification_status=value['verification_status'], version=value['version'],
                    verified_at=value.get('verified_at'), verification_error_code=value.get('verification_error_code'))

    def record_verification(self, tenant, reference, app_id, *, error_code=None):
        """Trusted server test result; version-CAS, never a public boolean setter."""
        from app.wechat_connection import ERRORS
        if error_code is not None and error_code not in ERRORS: raise blocked()
        validate_reference(reference, tenant, environment=self.environment)
        with self._locked(tenant) as (path, codec):
            value = self._read(path, codec, tenant)
            if (not value or value['state'] != 'active' or reference != self._reference(value)
                    or value['app_id'] != app_id): raise blocked('WECHAT_SECRET_VERSION_CONFLICT')
            value.update(verification_status='failed' if error_code else 'connected',
                         verified_at=datetime.now(timezone.utc).isoformat(), verification_error_code=error_code)
            self._write(path, codec, value)


def backend_from_settings(settings):
    return ProtectedTenantSecretBackend(Path(settings.data_dir)/'tenant-secrets'/settings.environment,
        settings.environment, getattr(settings, 'tenant_secret_key_file', None))
